version: '3.7'

services:

  postgres:
    container_name: sqlbuilder-postgres
    image: postgres:alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
      - sqlbuilder
    env_file:
      - .env

networks:
  sqlbuilder:
    name: sqlbuilder
